use crate::Capability;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum CommandCode {
    Echo = 0x01,
    CreateSession = 0x03,
    AuthenticateSession = 0x04,
    SessionMessage = 0x05,
    GetDeviceInfo = 0x06,
    ResetDevice = 0x08,
    GetDevicePublicKey = 0x0a,
    CloseSession = 0x40,
    GetStorageInfo = 0x41,
    PutOpaque = 0x42,
    GetOpaque = 0x43,
    PutAuthenticationKey = 0x44,
    PutAsymmetricKey = 0x45,
    GenerateAsymmetricKey = 0x46,
    SignPkcs1 = 0x47,
    ListObjects = 0x48,
    DecryptPkcs1 = 0x49,
    ExportWrapped = 0x4a,
    ImportWrapped = 0x4b,
    PutWrapKey = 0x4c,
    GetLogEntries = 0x4d,
    GetObjectInfo = 0x4e,
    SetOption = 0x4f,
    GetOption = 0x50,
    GetPseudoRandom = 0x51,
    PutHmacKey = 0x52,
    SignHmac = 0x53,
    GetPublicKey = 0x54,
    SignPss = 0x55,
    SignEcdsa = 0x56,
    DeriveEcdh = 0x57,
    DeleteObject = 0x58,
    DecryptOaep = 0x59,
    GenerateHmacKey = 0x5a,
    GenerateWrapKey = 0x5b,
    VerifyHmac = 0x5c,
    SignSshCertificate = 0x5d,
    PutTemplate = 0x5e,
    GetTemplate = 0x5f,
    DecryptOtp = 0x60,
    CreateOtpAead = 0x61,
    RandomizeOtpAead = 0x62,
    RewrapOtpAead = 0x63,
    SignAttestationCertificate = 0x64,
    PutOtpAeadKey = 0x65,
    GenerateOtpAeadKey = 0x66,
    SetLogIndex = 0x67,
    WrapData = 0x68,
    UnwrapData = 0x69,
    SignEddsa = 0x6a,
    BlinkDevice = 0x6b,
    ChangeAuthenticationKey = 0x6c,
    PutSymmetricKey = 0x6d,
    GenerateSymmetricKey = 0x6e,
    DecryptEcb = 0x6f,
    EncryptEcb = 0x70,
    DecryptCbc = 0x71,
    EncryptCbc = 0x72,
    PutPublicWrapKey = 0x73,
    GetRsaWrappedKey = 0x74,
    PutRsaWrappedKey = 0x75,
    ExportRsaWrapped = 0x76,
    ImportRsaWrapped = 0x77,
}

impl CommandCode {
    pub fn from_byte(value: u8) -> Option<Self> {
        use CommandCode::*;
        Some(match value {
            0x01 => Echo,
            0x03 => CreateSession,
            0x04 => AuthenticateSession,
            0x05 => SessionMessage,
            0x06 => GetDeviceInfo,
            0x08 => ResetDevice,
            0x0a => GetDevicePublicKey,
            0x40 => CloseSession,
            0x41 => GetStorageInfo,
            0x42 => PutOpaque,
            0x43 => GetOpaque,
            0x44 => PutAuthenticationKey,
            0x45 => PutAsymmetricKey,
            0x46 => GenerateAsymmetricKey,
            0x47 => SignPkcs1,
            0x48 => ListObjects,
            0x49 => DecryptPkcs1,
            0x4a => ExportWrapped,
            0x4b => ImportWrapped,
            0x4c => PutWrapKey,
            0x4d => GetLogEntries,
            0x4e => GetObjectInfo,
            0x4f => SetOption,
            0x50 => GetOption,
            0x51 => GetPseudoRandom,
            0x52 => PutHmacKey,
            0x53 => SignHmac,
            0x54 => GetPublicKey,
            0x55 => SignPss,
            0x56 => SignEcdsa,
            0x57 => DeriveEcdh,
            0x58 => DeleteObject,
            0x59 => DecryptOaep,
            0x5a => GenerateHmacKey,
            0x5b => GenerateWrapKey,
            0x5c => VerifyHmac,
            0x5d => SignSshCertificate,
            0x5e => PutTemplate,
            0x5f => GetTemplate,
            0x60 => DecryptOtp,
            0x61 => CreateOtpAead,
            0x62 => RandomizeOtpAead,
            0x63 => RewrapOtpAead,
            0x64 => SignAttestationCertificate,
            0x65 => PutOtpAeadKey,
            0x66 => GenerateOtpAeadKey,
            0x67 => SetLogIndex,
            0x68 => WrapData,
            0x69 => UnwrapData,
            0x6a => SignEddsa,
            0x6b => BlinkDevice,
            0x6c => ChangeAuthenticationKey,
            0x6d => PutSymmetricKey,
            0x6e => GenerateSymmetricKey,
            0x6f => DecryptEcb,
            0x70 => EncryptEcb,
            0x71 => DecryptCbc,
            0x72 => EncryptCbc,
            0x73 => PutPublicWrapKey,
            0x74 => GetRsaWrappedKey,
            0x75 => PutRsaWrappedKey,
            0x76 => ExportRsaWrapped,
            0x77 => ImportRsaWrapped,
            _ => return None,
        })
    }

    pub fn required_session_capability(self) -> Option<Capability> {
        use CommandCode::*;
        match self {
            PutOpaque => Some(Capability::PutOpaque),
            GetOpaque => Some(Capability::GetOpaque),
            PutAuthenticationKey => Some(Capability::PutAuthenticationKey),
            PutAsymmetricKey => Some(Capability::PutAsymmetricKey),
            GenerateAsymmetricKey => Some(Capability::GenerateAsymmetricKey),
            SignPkcs1 => Some(Capability::SignPkcs),
            DecryptPkcs1 => Some(Capability::DecryptPkcs),
            ExportWrapped | ExportRsaWrapped | GetRsaWrappedKey => Some(Capability::ExportWrapped),
            ImportWrapped | ImportRsaWrapped => Some(Capability::ImportWrapped),
            PutWrapKey => Some(Capability::PutWrapKey),
            PutRsaWrappedKey => Some(Capability::ImportWrapped),
            GetLogEntries => Some(Capability::GetLogEntries),
            SetOption | SetLogIndex => Some(Capability::SetOption),
            GetOption => Some(Capability::GetOption),
            GetPseudoRandom => Some(Capability::GetPseudoRandom),
            PutHmacKey => Some(Capability::PutMacKey),
            SignHmac => Some(Capability::SignHmac),
            SignPss => Some(Capability::SignPss),
            SignEcdsa => Some(Capability::SignEcdsa),
            DeriveEcdh => Some(Capability::DeriveEcdh),
            DecryptOaep => Some(Capability::DecryptOaep),
            GenerateHmacKey => Some(Capability::GenerateHmacKey),
            GenerateWrapKey => Some(Capability::GenerateWrapKey),
            VerifyHmac => Some(Capability::VerifyHmac),
            SignSshCertificate => Some(Capability::SignSshCertificate),
            PutTemplate => Some(Capability::PutTemplate),
            GetTemplate => Some(Capability::GetTemplate),
            DecryptOtp => Some(Capability::DecryptOtp),
            CreateOtpAead => Some(Capability::CreateOtpAead),
            RandomizeOtpAead => Some(Capability::RandomizeOtpAead),
            SignAttestationCertificate => Some(Capability::SignAttestationCertificate),
            PutOtpAeadKey => Some(Capability::PutOtpAeadKey),
            GenerateOtpAeadKey => Some(Capability::GenerateOtpAeadKey),
            WrapData => Some(Capability::WrapData),
            UnwrapData => Some(Capability::UnwrapData),
            SignEddsa => Some(Capability::SignEddsa),
            ChangeAuthenticationKey => Some(Capability::ChangeAuthenticationKey),
            PutSymmetricKey => Some(Capability::PutSymmetricKey),
            GenerateSymmetricKey => Some(Capability::GenerateSymmetricKey),
            DecryptEcb => Some(Capability::DecryptEcb),
            EncryptEcb => Some(Capability::EncryptEcb),
            DecryptCbc => Some(Capability::DecryptCbc),
            EncryptCbc => Some(Capability::EncryptCbc),
            PutPublicWrapKey => Some(Capability::PutPublicWrapKey),
            ResetDevice => Some(Capability::ResetDevice),
            RewrapOtpAead | DeleteObject | Echo | CreateSession | AuthenticateSession
            | SessionMessage | GetDeviceInfo | GetDevicePublicKey | CloseSession
            | GetStorageInfo | ListObjects | GetObjectInfo | GetPublicKey | BlinkDevice => None,
        }
    }
}
