[package]
name = "virtual-yubihsm"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
description = "A privilege-separated software implementation of the YubiHSM 2 device protocol"
license = "MIT OR Apache-2.0"
publish = false

[workspace]
members = [
    "crates/virtual-yubihsm-i2c",
    "crates/virtual-yubihsm-core",
    "crates/yubihsm-qualification",
]
resolver = "2"

[workspace.dependencies]
software-key-core = { path = "../software-key-core" }

[features]
default = ["firmware-full"]
firmware-yubihsm2 = ["virtual-yubihsm-core/firmware-yubihsm2"]
firmware-secure-channel = ["virtual-yubihsm-core/firmware-secure-channel"]
firmware-full = ["virtual-yubihsm-core/firmware-full"]

[dependencies]
libc = "0.2.189"
usb-gadget-worker = { path = "../usb-gadget-supervisor/crates/usb-gadget-worker" }
virtual-yubihsm-core = { path = "crates/virtual-yubihsm-core", default-features = false, features = ["persistent-runtime"] }

[target.'cfg(target_os = "linux")'.dependencies]
display-backends = { path = "../display-backends" }
gpiocdev-uapi = "0.7.0"

[[bin]]
name = "virtual-yubihsm-worker"
path = "src/main.rs"

[patch.crates-io]
# Reduce ML-DSA matrix stack usage without changing public lattice types.
ml-dsa = { git = "https://github.com/qpernil/signatures.git", rev = "e06d2e28699428fbcc135c388516883bbb71f170" }
